language: c

sudo: false

env:
  global:
    - LUAROCKS=3.0.3
  matrix:
    - LUA=lua5.2

jobs:
  include:
    - stage: "test"
      name: "Unit Tests"
      script: busted
    - stage: "package"
      name: "Create Release Package"

      script: ./package.sh -y

before_install:
  - source .travis/setenv_lua.sh
  - chmod +x ./package.sh
  - luarocks install busted