language: c

sudo: false

env:
  global:
    - LUAROCKS=3.0.3
  matrix:
    - LUA=lua5.2

branches:
  only:
    - master
    - develop
    - /^release/.*$/

jobs:
  include:
    - stage: "test"
      name: "Unit Tests"
      script: busted
    - stage: "package"
      name: "Create Release Package"
      if: branch = master
      script: ./package.sh -y

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted